<template>
  <div id="app">
    <button @click="load">加载</button>
    <button @click="load2">加载2</button>
    <h1>Vue Gantt Line Table Demo</h1>
    <div class="ganttBox">
      <GanttLineTable ref="GanttLineTableRef" :ganttOption="chartStatus" :source="ganttData" :statusColor="colorConfig">
        <template #content="{ bar }">
          <lineNode
            :key="bar.ganttBarConfig.id"
            :class="`row-item ${bar.nodeConfig.nodeLabelType} ${bar.nodeConfig.startLabel} ${bar.nodeConfig.nodeId.includes('__LineTable.node.ft') ? 'offset' : ''}`"
            :style="{ '--color': bar.strokeColor, '--top': '0px', transform: `translateY(${bar.translateY}px)` }"
            :nodeLabel="bar.nodeConfig.info ? bar.nodeConfig.info : bar.nodeConfig.nodeDesc"
            :time="dayjs(bar.nodeConfig.nodeStartDate).format('MM/DD')"
            :betweenNodeLabel="bar.nodeConfig.nodeRemark"
            :projectLabel="bar.projectDesc"
            :nodeConfig="bar.nodeConfig"
            @updateValue="handleUpdate"
          ></lineNode>
        </template>
      </GanttLineTable>
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref } from "vue";
import dayjs from "dayjs";
import GanttLineTable from "./components/GanttLineTable.vue";
const GanttLineTableRef = ref();
const chartStatus = ref({
  chartStart: dayjs("2022-01-01").startOf("year").format("YYYY-MM-DD"),
  chartEnd: dayjs("2026-12-31").endOf("year").format("YYYY-MM-DD"),
  precision: "month",
  dateFormat: "YYYY-MM-DD",
  colorScheme: "default",
  hideTimeaxis: false,
  grid: true,
  currentTime: false,
  currentTimeLabel: "显示在当前时间标记旁边的文本槽",
  rowHeight: 120,
  labelColumnTitle: "资源",
  labelColumnWidth: "150px",
  barStart: "beginDate",
  barEnd: "endDate",
});
const data = {
  startTime: "2024-04-01",
  endTime: "2028-9-30",
  table: [
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606555905",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "1#滑道", //重要
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006", //重要
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "204460603266555905",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "1#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606032665559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "2#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606032665559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "2#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606032665559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "2#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606032665559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "2#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606555905",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "3#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "2044360655590",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "3#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "204436065559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "3#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606555",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "3#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "2044360655",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "3#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "3#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
  ],
};
const data2 = {
  startTime: "2024-04-01",
  endTime: "2028-9-30",
  table: [
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606555905",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "1#滑道", //重要
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006", //重要
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "204460603266555905",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "1#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "1#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606032665559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "2#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
    {
      projectDesc: "M026 SBM 111 330*60", //图形开始描述（项目号+船东+项目描述+尺寸）//缺失
      下水: null,
      半船移位3反馈: null,
      铺底3: null,
      半船移位3: "2027-08-01",
      半船移位2: "2027-06-01",
      半船移位1: "2027-04-01",
      半船移位1反馈: null,
      planName: null,
      "总组P/E": null,
      铺底2: null,
      试航反馈: null,
      关键节点1: null,
      开工反馈: null,
      关键节点1反馈: null,
      id: "20443606032665559",
      合同生效3反馈: null,
      下水2反馈: null,
      关键节点3反馈: null,
      合同交付反馈: null,
      enabledMark: 1,
      "计划交付P/L反馈": null,
      关键节点2: "2027-12-01",
      sortCode: 1,
      关键节点3: null,
      铺底2反馈: null,
      "计划交付P/L": null,
      shipNo: "BXQ2230024",
      detailList: [
        {
          startLabel: "left-triangle",
          nodeLabelType: "dot-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.vcDate",
          nodeCode: "V/C",
          nodeStartDate: "2026-04-01",
          nodeDesc: "合同生效",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "",
          nodeLabelType: "line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.scDate",
          nodeCode: "S/C",
          nodeStartDate: "2026-08-08",
          nodeDesc: "开工",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft1Date",
          nodeCode: "F/T1",
          nodeStartDate: "2027-04-01",
          nodeDesc: "半船移位1",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft2Date",
          nodeCode: "F/T2",
          nodeStartDate: "2027-06-01",
          nodeDesc: "半船移位2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "turn-point",
          nodeLabelType: "bold-line",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.ft3Date",
          nodeCode: "F/T3",
          nodeStartDate: "2027-08-01",
          nodeDesc: "半船移位3",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
        {
          startLabel: "star",
          nodeLabelType: "",
          shipStatus: "生效",
          siteName: "2#滑道",
          shipNo: "BXQ2230024",
          enabledMark: null,
          nodeId: "__LineTable.node.keyPoinit2Date",
          nodeCode: "KEYPOINT2",
          nodeStartDate: "2027-12-01",
          nodeDesc: "关键节点2",
          info: null,
          nodeRemark: null,
          shipSortSn: 1,
        },
      ],
      "总组P/E反馈": null,
      下水反馈: null,
      半船移位2反馈: null,
      合同交付: null,
      试航2: null,
      siteName: "2#滑道",
      铺底: null,
      shipDesc: "新鞍钢保修",
      试航2反馈: null,
      铺底反馈: null,
      合同生效2反馈: null,
      合同生效3: null,
      合同生效2: null,
      下水3反馈: null,
      关键节点2反馈: null,
      shipStatus: "生效",
      siteCode: "CD0006",
      试航: null,
      renameInfo: null,
      "项目完工P/C": null,
      开工: "2026-08-08",
      铺底3反馈: null,
      合同生效: "2026-04-01",
      "项目完工P/C反馈": null,
      合同生效反馈: null,
      下水3: null,
      下水2: null,
    },
  ],
};
const ganttData = ref(data.table);
chartStatus.value.chartStart = dayjs(dayjs(data.startTime).format("YYYY-MM-01")).subtract(6, "month").format("YYYY-MM-DD");
chartStatus.value.chartEnd = dayjs(dayjs(data.endTime).format(`YYYY-MM-${dayjs(data.endTime).daysInMonth()}`))
  .add(6, "month")
  .format("YYYY-MM-DD");

const load = () => {
  ganttData.value = data.table;
  chartStatus.value.chartStart = dayjs(dayjs(data.startTime).format("YYYY-MM-01")).subtract(3, "month").format("YYYY-MM-DD");
  chartStatus.value.chartEnd = dayjs(dayjs(data.endTime).format(`YYYY-MM-${dayjs(data.endTime).daysInMonth()}`))
    .add(3, "month")
    .format("YYYY-MM-DD");
  nextTick(() => {
    if (GanttLineTableRef.value) {
      GanttLineTableRef.value.init();
    }
  });
};
const load2 = () => {
  ganttData.value = data2.table;
  chartStatus.value.chartStart = dayjs(dayjs(data.startTime).format("YYYY-MM-01")).subtract(5, "month").format("YYYY-MM-DD");
  chartStatus.value.chartEnd = dayjs(dayjs(data.endTime).format(`YYYY-MM-${dayjs(data.endTime).daysInMonth()}`))
    .add(5, "month")
    .format("YYYY-MM-DD");
  nextTick(() => {
    if (GanttLineTableRef.value) {
      GanttLineTableRef.value.init();
    }
  });
};
import lineNode from "./components/lineNode.vue";
const colorConfig = {
  "热点项目(可能性高)": "#FF0000",
  "在谈项目(可能性中)": "#90ee90",
  已交船: "#838383",
  待生效: "#0000FF",
  生效: "#0000FF",
  开工: "#000000",
  已下水: "#000000",
  已进坞: "#000000",
  //以下暂定
  "跟踪项目(可能性低)": "#A9A9A9",
  规划: "#A9A9A9",
  结束: "#A9A9A9",
  //   background-color: #90ee90; /* 在谈 */
  //   background-color: #0000ff; /* 待生效 */
  //   background-color: #838383; /* 交船 */
  //   background-color: #ff0000; /* 热点 */
  //   background-color: #000000; /* 开工、规划、已进坞、已下水 */
  //   background-color: #a9a9a9; /* 结束 */
};
const handleUpdate = (val: any) => {
  console.log(val, "收到喽");
};
</script>

<style>
@import "./components/index.css";

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.ganttBox {
  width: 90%;
  height: 700px;
  transform: translateX(5%);
  border: 5px solid #ccc;
  box-sizing: border-box;
}
</style>
